export const defaultSettings = {
  simple: true,
  simpleFormat: "normal",
  channels: 1,
  rate: 64000,
  voiceBitrate: 384000,
  pacsize: 960,
  freq: 48000,
  attenuationFactor: 1,
  attenuation: false,
  customChannels: true,
  customFreq: true,
  customPacsize: true,
  customRate: true,
  customVoiceBitrate: false,
  priority: false,
  stereo: false,
  fec: false,
  monoDecoding: false,
  resetVolume: false
};

export const simpleFormats = {
  low: {
    channels: 0.5,
    rate: 32000,
    voiceBitrate: 192000,
    pacsize: 480,
    freq: 24000,
    attenuationFactor: 0,
    attenuation: false,
    customChannels: true,
    customFreq: true,
    customPacsize: true,
    customRate: true,
    customVoiceBitrate: true,
  },
  normal: {
    channels: 1,
    rate: 64000,
    voiceBitrate: 384000,
    pacsize: 960,
    freq: 48000,
    attenuationFactor: 1,
    attenuation: false,
    customChannels: false,
    customFreq: false,
    customPacsize: false,
    customRate: false,
    customVoiceBitrate: false,
  },
  medium: {
    channels: 4,
    rate: 128000,
    voiceBitrate: 384000,
    pacsize: 1920,
    freq: 96000,
    attenuationFactor: 1,
    attenuation: true,
    customChannels: true,
    customFreq: true,
    customPacsize: true,
    customRate: true,
    customVoiceBitrate: true,
  },
  high: {
    channels: 8,
    rate: 256000,
    voiceBitrate: 1536000,
    pacsize: 3840,
    freq: 192000,
    attenuationFactor: 25,
    attenuation: false,
    customChannels: true,
    customFreq: true,
    customPacsize: true,
    customRate: true,
    customVoiceBitrate: true,
  },
  ultra: {
    channels: 16,
    rate: 512000,
    voiceBitrate: 3072000,
    pacsize: 7680,
    freq: 384000,
    attenuationFactor: 50,
    attenuation: true,
    customChannels: true,
    customFreq: true,
    customPacsize: true,
    customRate: true,
    customVoiceBitrate: true,
  },
  orgasm: {
    channels: 32,
    rate: 683000,
    voiceBitrate: 6144000,
    pacsize: 15360,
    freq: 768000,
    attenuationFactor: 100,
    attenuation: true,
    customChannels: true,
    customFreq: true,
    customPacsize: true,
    customRate: true,
    customVoiceBitrate: true,
  },
} as const;
